'use client'
import { useEffect, useMemo, useState } from 'react'

type Candidate={rank:number;symbol:string;name:string;sector:string;score:number;moveQuality?:number;bias:'LONG'|'SHORT';change:number;volume:string;rs:string;setup:string;confidence:string;lastPrice:number;oi:number|null;rvol?:number;rangePct?:number;nr4?:boolean;nr7?:boolean;pdBreak?:string;t1Date?:string;marketDirection?:string;marketAligned?:boolean;openingRangeBreak?:boolean;extremeVolume?:boolean;signalTime?:string;filterDate?:string;hourlyCompression?:boolean;hourlyTrend?:boolean;weeklyRoom?:number;monthlyRoom?:number;dailyLocation?:string}
type IndexQuote={title:string;value:number|null;change:number|null}
type MarketResponse={ok:boolean;source?:string;timestamp?:string;candidates?:Candidate[];indexes?:IndexQuote[];error?:string;filterDate?:string;diagnostics?:{scanned?:number;candidates?:number;marketHours?:boolean;marketDirection?:string;niftyChange?:number}}
type MoveFilter='ALL'|'UP1'|'UP2'|'DOWN1'|'DOWN2'
const fallbackIndexes:IndexQuote[]=[{title:'NIFTY 50',value:null,change:null},{title:'BANK NIFTY',value:null,change:null},{title:'NIFTY MIDCAP',value:null,change:null},{title:'INDIA VIX',value:null,change:null}]
export default function Home(){
 const[query,setQuery]=useState(''),[showLong,setShowLong]=useState(true),[showShort,setShowShort]=useState(true),[activeTab,setActiveTab]=useState<'LIVE'|'HISTORICAL'>('LIVE'),[moveFilter,setMoveFilter]=useState<MoveFilter>('ALL'),[moveMenu,setMoveMenu]=useState(false),[moveSort,setMoveSort]=useState<'NONE'|'DESC'|'ASC'>('NONE'),[candidates,setCandidates]=useState<Candidate[]>([]),[historicalCandidates,setHistoricalCandidates]=useState<Candidate[]>([]),[indexes,setIndexes]=useState<IndexQuote[]>(fallbackIndexes),[loading,setLoading]=useState(true),[historicalLoading,setHistoricalLoading]=useState(true),[error,setError]=useState(''),[historicalError,setHistoricalError]=useState(''),[lastUpdated,setLastUpdated]=useState(''),[historicalDate,setHistoricalDate]=useState(''),[diagnostics,setDiagnostics]=useState<MarketResponse['diagnostics']>({}),[historicalDiagnostics,setHistoricalDiagnostics]=useState<MarketResponse['diagnostics']>({})
 const loadMarketData=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/market',{cache:'no-store'}),d:MarketResponse=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Market data unavailable');setCandidates(d.candidates??[]);setIndexes(d.indexes??fallbackIndexes);setDiagnostics(d.diagnostics??{});setLastUpdated(d.timestamp??new Date().toISOString())}catch(e){setError(e instanceof Error?e.message:'Unable to load market data')}finally{setLoading(false)}}
 const loadHistoricalData=async()=>{setHistoricalLoading(true);setHistoricalError('');try{const r=await fetch('/api/historical',{cache:'no-store'}),d:MarketResponse=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Historical data unavailable');setHistoricalCandidates(d.candidates??[]);setHistoricalDate(d.filterDate??d.candidates?.[0]?.filterDate??'');setHistoricalDiagnostics(d.diagnostics??{})}catch(e){setHistoricalError(e instanceof Error?e.message:'Unable to load historical scan')}finally{setHistoricalLoading(false)}}
 useEffect(()=>{loadMarketData();loadHistoricalData();const t=window.setInterval(loadMarketData,30000);return()=>window.clearInterval(t)},[])
 const activeCandidates=activeTab==='LIVE'?candidates:historicalCandidates,activeLoading=activeTab==='LIVE'?loading:historicalLoading,activeError=activeTab==='LIVE'?error:historicalError,activeDiagnostics=activeTab==='LIVE'?diagnostics:historicalDiagnostics
 const filtered=useMemo(()=>{const rows=activeCandidates.filter(c=>{const match=`${c.symbol} ${c.name} ${c.sector}`.toLowerCase().includes(query.toLowerCase()),bias=(c.bias==='LONG'&&showLong)||(c.bias==='SHORT'&&showShort),m=c.change,moveOk=moveFilter==='ALL'||moveFilter==='UP1'&&m>=1||moveFilter==='UP2'&&m>=2||moveFilter==='DOWN1'&&m<=-1||moveFilter==='DOWN2'&&m<=-2;return match&&bias&&moveOk});if(moveSort==='NONE')return rows;return[...rows].sort((a,b)=>moveSort==='DESC'?b.change-a.change:a.change-b.change)},[activeCandidates,query,showLong,showShort,moveFilter,moveSort])
 const aPlus=activeCandidates.filter(c=>c.score>=90).length,extremeCount=activeCandidates.filter(c=>c.extremeVolume).length,orbCount=activeCandidates.filter(c=>c.openingRangeBreak).length,mqPrime=activeCandidates.filter(c=>(c.moveQuality??0)>=90).length,marketDirection=activeDiagnostics?.marketDirection,longCount=activeCandidates.filter(c=>c.bias==='LONG').length,shortCount=activeCandidates.filter(c=>c.bias==='SHORT').length,regime=marketDirection==='LONG'?'BULLISH':marketDirection==='SHORT'?'BEARISH':longCount>=shortCount?'BULLISH':'NEUTRAL'
 const pattern=useMemo(()=>{if(activeTab!=='HISTORICAL'||!activeCandidates.length)return null;const gainers=[...activeCandidates].sort((a,b)=>b.change-a.change);const top=gainers[0];const n=activeCandidates.length;const count=(fn:(c:Candidate)=>boolean)=>activeCandidates.filter(fn).length;const avg=(fn:(c:Candidate)=>number)=>{const a=activeCandidates.map(fn).filter(x=>Number.isFinite(x));return a.length?a.reduce((x,y)=>x+y,0)/a.length:0};const pdh=count(c=>c.pdBreak==='PDH'),pdl=count(c=>c.pdBreak==='PDL'),rs=count(c=>c.rs==='Strong'),ext=count(c=>!!c.extremeVolume),orb=count(c=>!!c.openingRangeBreak),base=count(c=>c.dailyLocation==='BASE/LOWER RANGE'||c.dailyLocation==='BASE/UPPER RANGE'),hcomp=count(c=>!!c.hourlyCompression),htrend=count(c=>!!c.hourlyTrend),nr=count(c=>!!c.nr4||!!c.nr7),rooms=avg(c=>(c.weeklyRoom??0)+(c.monthlyRoom??0));const common=[{label:'Extreme 5M volume',pct:ext/n*100,count:ext},{label:'Opening-range break',pct:orb/n*100,count:orb},{label:'Relative strength',pct:rs/n*100,count:rs},{label:'PDH/PDL break',pct:Math.max(pdh,pdl)/n*100,count:Math.max(pdh,pdl)},{label:'Base / lower-range location',pct:base/n*100,count:base},{label:'1H compression',pct:hcomp/n*100,count:hcomp},{label:'1H up/down trend',pct:htrend/n*100,count:htrend},{label:'NR4 / NR7 structure',pct:nr/n*100,count:nr}].sort((a,b)=>b.pct-a.pct);return{top,common,avgRoom:rooms,pdh,pdl,rs,ext,orb,base,hcomp,htrend,nr}},[activeTab,activeCandidates])
 const prettyHistoricalDate=historicalDate?new Date(`${historicalDate}T00:00:00+05:30`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase():'PREVIOUS SESSION',moveLabel=moveFilter==='ALL'?'MOVE':moveFilter==='UP1'?'MOVE ≥ +1%':moveFilter==='UP2'?'MOVE ≥ +2%':moveFilter==='DOWN1'?'MOVE ≤ -1%':'MOVE ≤ -2%'
 return <main className="shell">
  <header className="topbar"><div className="brand"><div className="logo">PT</div><div><div className="brand-title">PT MOVE SCANNER</div><div className="brand-sub">Probability-based intraday intelligence</div></div></div><div className="top-actions"><span className="market-status"><i/> Market data: {loading?'Connecting…':error?'Offline':'LIVE'}</span><span className="date">{lastUpdated?new Date(lastUpdated).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase():'—'}</span><button className="refresh" onClick={()=>{loadMarketData();loadHistoricalData()}}>↻ Refresh</button></div></header>
  <section className="hero"><div><div className="eyebrow">{activeTab==='LIVE'?'LIVE → F&O MOMENTUM TERMINAL':`HISTORICAL → ${prettyHistoricalDate}`}</div><h1>Find the stocks <span>before the move.</span></h1><p>{activeTab==='LIVE'?'Live Upstox data scans the NSE F&O universe for high-volume 5-minute PDH/PDL breaks, opening-range confirmation, relative strength, market direction and NR4/NR7 structure.':`Historical replay of the same scanner logic for ${prettyHistoricalDate}. Technical Score is unchanged; Move Quality adds Daily + Weekly + Monthly + 1H context.`}</p></div><div className="regime-card"><div className="small-label">MARKET REGIME</div><div className="regime">{regime} <b>{regime==='BULLISH'?'↑':regime==='BEARISH'?'↓':'→'}</b></div><div className="muted">NIFTY 50 direction confirmation</div></div></section>
  <section className="index-grid">{indexes.map(x=><IndexCard key={x.title} title={x.title} value={x.value==null?'—':x.value.toLocaleString('en-IN',{maximumFractionDigits:2})} change={x.change==null?'—':`${x.change>=0?'+':''}${x.change.toFixed(2)}%`} positive={(x.change??0)>=0}/>)}</section>
  <section className="control-row"><div className="tabs"><button className={activeTab==='LIVE'?'active':''} onClick={()=>setActiveTab('LIVE')}>LIVE</button><button className={activeTab==='HISTORICAL'?'active':''} onClick={()=>setActiveTab('HISTORICAL')}>HISTORICAL</button></div><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search stock, sector..."/></div><div className="move-filter-wrap"><button className={`filter move-filter ${moveFilter!=='ALL'?'on':''}`} onClick={()=>setMoveMenu(v=>!v)}>↕ {moveLabel}</button>{moveMenu&&<div className="move-menu"><button onClick={()=>{setMoveFilter('ALL');setMoveMenu(false)}}>ALL MOVES</button><button onClick={()=>{setMoveFilter('UP1');setMoveMenu(false)}}>GAINERS ≥ +1%</button><button onClick={()=>{setMoveFilter('UP2');setMoveMenu(false)}}>GAINERS ≥ +2%</button><button onClick={()=>{setMoveFilter('DOWN1');setMoveMenu(false)}}>LOSERS ≤ -1%</button><button onClick={()=>{setMoveFilter('DOWN2');setMoveMenu(false)}}>LOSERS ≤ -2%</button></div>}</div><button className={`filter ${showLong?'on':''}`} onClick={()=>setShowLong(v=>!v)}>● LONG</button><button className={`filter short ${showShort?'on':''}`} onClick={()=>setShowShort(v=>!v)}>● SHORT</button></section>
  <section className="stats-row"><Stat label="F&O CANDIDATES" value={String(activeCandidates.length)} note={activeDiagnostics?.scanned?`${activeDiagnostics.scanned} F&O stocks scanned`:activeTab==='LIVE'?'Live qualified results':`Filtered on ${prettyHistoricalDate}`}/><Stat label="EXTREME VOLUME" value={String(extremeCount)} note="5m volume ≥ 2.5× average"/><Stat label="OPENING RANGE" value={String(orbCount)} note="15m high/low confirmation"/><Stat label="PRIME MOVE QUALITY" value={String(mqPrime)} note="MTF Move Quality ≥ 90"/></section>
  <section className="content-grid"><div className="panel candidates-panel"><div className="panel-head"><div><div className="panel-title">{activeTab==='LIVE'?'LIVE F&O MOVE CANDIDATES':`HISTORICAL FILTERED STOCKS — ${prettyHistoricalDate}`}</div><div className="panel-sub">{activeTab==='LIVE'?'5m ≥2× volume + PDH/PDL break + momentum / RS confirmation':'Technical Score unchanged • Move Quality = Daily + Weekly + Monthly + 1H + 5M context'}</div></div><span className="live-pill"><i/> {activeLoading?'SCANNING':activeError?'ERROR':activeTab}</span></div>
  <div className="table-wrap"><table><thead><tr><th>#</th><th>STOCK</th><th>SCORE</th><th>MOVE QUALITY</th><th>BIAS</th><th><button className={`th-button ${moveSort!=='NONE'?'selected':''}`} onClick={()=>setMoveSort(v=>v==='NONE'?'DESC':v==='DESC'?'ASC':'NONE')}>MOVE {moveSort==='DESC'?'↓':moveSort==='ASC'?'↑':'↕'}</button></th><th>RVOL</th><th>RS</th><th>SETUP</th></tr></thead><tbody>{filtered.map(c=><tr key={c.symbol}><td className="rank">{String(c.rank).padStart(2,'0')}</td><td><div className="stock"><strong>{c.symbol}</strong><span>{c.name}</span></div></td><td><Score value={c.score}/></td><td><MoveQuality value={c.moveQuality}/></td><td><span className={`bias ${c.bias.toLowerCase()}`}>{c.bias==='LONG'?'↑':'↓'} {c.bias}</span></td><td className={c.change>=0?'up':'down'}>{c.change>0?'+':''}{c.change.toFixed(2)}%</td><td className="volume">{c.rvol?.toFixed(2)}×</td><td>{c.rs}</td><td><span className="setup">{c.setup}</span></td></tr>)}{!activeLoading&&!filtered.length&&<tr><td colSpan={9} style={{padding:'28px',textAlign:'center'}}>{activeError||(activeTab==='LIVE'?'No live F&O candidates match the confirmation filters right now.':`No stocks passed the historical filters for ${prettyHistoricalDate}.`)}</td></tr>}</tbody></table></div></div>
  <aside className="panel sector-panel"><div className="panel-head"><div><div className="panel-title">SECTOR LEADERSHIP</div><div className="panel-sub">Relative performance of qualified {activeTab.toLowerCase()} candidates</div></div></div>{sectorRows(activeCandidates).map(([n,s,m])=><div className="sector" key={n}><div className="sector-top"><span>{n}</span><b>{m}</b></div><div className="bar"><i style={{width:`${s}%`}}/></div><div className="sector-foot"><span>{activeTab==='LIVE'?'Live RS proxy':'Historical RS'}</span><span>{s}</span></div></div>)}</aside></section>
  {activeTab==='HISTORICAL'&&pattern&&<section className="pattern-panel panel"><div className="panel-head"><div><div className="panel-title">TOP GAINER PATTERN ANALYZER</div><div className="panel-sub">What the qualified historical gainers had in common BEFORE the move</div></div><span className="live-pill"><i/> RESEARCH</span></div><div style={{display:'grid',gridTemplateColumns:'1.15fr 1fr',gap:18}}><div style={{border:'1px solid rgba(255,255,255,.08)',borderRadius:14,padding:18}}><div className="small-label">TOP HISTORICAL GAINER</div><div style={{display:'flex',alignItems:'baseline',gap:12,marginTop:8}}><strong style={{fontSize:28}}>{pattern.top.symbol}</strong><span className={pattern.top.change>=0?'up':'down'} style={{fontSize:20,fontWeight:700}}>{pattern.top.change>=0?'+':''}{pattern.top.change.toFixed(2)}%</span></div><div className="muted" style={{marginTop:4}}>Technical Score {pattern.top.score} • Move Quality {pattern.top.moveQuality??'—'} • {pattern.top.bias}</div><div style={{marginTop:14,display:'flex',flexWrap:'wrap',gap:8}}><Badge text={pattern.top.extremeVolume?'EXTREME VOL':'NORMAL VOL'} good={!!pattern.top.extremeVolume}/><Badge text={pattern.top.openingRangeBreak?'ORB BREAK':'NO ORB'} good={!!pattern.top.openingRangeBreak}/><Badge text={pattern.top.rs==='Strong'?'RS STRONG':'RS NEUTRAL'} good={pattern.top.rs==='Strong'}/><Badge text={pattern.top.pdBreak==='PDH'?'PDH BREAK':pattern.top.pdBreak==='PDL'?'PDL BREAK':'NO PD BREAK'} good={!!pattern.top.pdBreak}/><Badge text={pattern.top.dailyLocation||'LOCATION —'} good={!!pattern.top.dailyLocation?.includes('BASE')}/></div></div><div style={{border:'1px solid rgba(255,255,255,.08)',borderRadius:14,padding:18}}><div className="small-label">COMMON PRE-MOVE FACTORS</div><div style={{marginTop:10}}>{pattern.common.slice(0,6).map(x=><div key={x.label} style={{marginBottom:10}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12}}><span>{x.label}</span><b>{x.count}/{activeCandidates.length}</b></div><div style={{height:6,borderRadius:99,background:'rgba(255,255,255,.08)',marginTop:5,overflow:'hidden'}}><i style={{display:'block',height:'100%',width:`${Math.min(100,x.pct)}%`,background:'var(--accent,#b8ff2c)'}}/></div></div>)}</div><div className="muted" style={{marginTop:6}}>Avg weekly + monthly room: {pattern.avgRoom.toFixed(2)}%</div></div></div><div className="muted" style={{marginTop:14}}>This is descriptive research, not a new entry filter. We should validate the same factors across many previous sessions before changing the scanner score.</div></section>}
  <section className="bottom-grid"><div className="panel signal-panel"><div className="panel-title">{activeTab==='LIVE'?'LIVE SCANNER LOGIC':'HISTORICAL REPLAY LOGIC'}</div><div className="logic-grid"><Logic n="01" title="TECHNICAL SCORE — UNCHANGED" text="Original PDH/PDL + volume + ORB + RS + market + NR4/NR7 + T-1 scoring remains untouched."/><Logic n="02" title="MOVE QUALITY — NEW" text="Separate 0–100 score using pre-move Daily location, Weekly/Monthly room, 1H compression/trend and 5M trigger quality."/><Logic n="03" title="5M TRIGGER" text="PDH/PDL break with ≥2× previous 20-candle volume; ≥2.5× is extreme, plus ORB and relative strength."/><Logic n="04" title="MTF CONTEXT" text="Move Quality rewards base/less-extended location, higher-timeframe room and 1H compression/trend. It does not alter Technical Score."/></div></div><div className="panel disclaimer"><div className="panel-title">MODEL STATUS</div><div className="status-line"><span className="dot"/> {activeError?'Connection error':activeTab==='LIVE'?'Upstox LIVE F&O scanner active':`Historical replay complete • ${prettyHistoricalDate}`}</div><p>{activeError?activeError:activeTab==='LIVE'?'Only stocks passing the configured multi-factor confirmation layer are displayed. Research and decision support only.':'Historical mode preserves the original Technical Score and adds a separate Move Quality score for MTF pre-move context.'}</p><div className="progress"><i style={{width:'90%'}}/></div><div className="muted">Data connector: UPSTOX LIVE + HISTORICAL</div></div></section>
  <footer><span>PT MOVE SCANNER • {activeTab==='LIVE'?'LIVE ENGINE':'HISTORICAL ENGINE'}</span><span>{activeTab==='LIVE'?'Auto-refresh: 30 seconds':`Previous completed session: ${prettyHistoricalDate}`} • NSE F&amp;O • Research &amp; decision support</span></footer>
 </main>
}
function Badge({text,good}:{text:string;good:boolean}){return <span style={{display:'inline-flex',alignItems:'center',padding:'6px 9px',borderRadius:999,border:'1px solid rgba(255,255,255,.1)',fontSize:10,fontWeight:700,letterSpacing:'.05em',background:good?'rgba(184,255,44,.08)':'rgba(255,255,255,.03)',color:good?'#b8ff2c':'#9aa3ad'}}>{text}</span>}
function sectorRows(candidates:Candidate[]):[string,number,string][]{const groups=new Map<string,number[]>();candidates.forEach(c=>groups.set(c.sector,[...(groups.get(c.sector)??[]),c.change]));return Array.from(groups.entries()).map(([name,changes])=>{const avg=changes.reduce((a,b)=>a+b,0)/changes.length,score=Math.max(10,Math.min(99,Math.round(50+avg*12)));return[name,score,`${avg>=0?'+':''}${avg.toFixed(2)}%`] as [string,number,string]}).sort((a,b)=>b[1]-a[1])}
function IndexCard({title,value,change,positive}:{title:string,value:string,change:string,positive?:boolean}){return <div className="index-card"><div className="small-label">{title}</div><div className="index-value">{value}</div><div className={positive?'up':'down'}>{change}</div><div className="spark"><span/><span/><span/><span/><span/><span/><span/></div></div>}
function Stat({label,value,note}:{label:string,value:string,note:string}){return <div className="stat"><div className="small-label">{label}</div><div className="stat-value">{value}</div><div className="muted">{note}</div></div>}
function Score({value}:{value:number}){return <div className="score"><b>{value}</b><span><i style={{width:`${value}%`}}/></span></div>}
function MoveQuality({value}:{value?:number}){const v=value??0;return <div className="score"><b>{value==null?'—':v}</b><span><i style={{width:`${v}%`}}/></span></div>}
function Logic({n,title,text}:{n:string,title:string,text:string}){return <div className="logic"><span>{n}</span><div><b>{title}</b><p>{text}</p></div></div>}
