'use client'
import {useEffect,useMemo,useState} from 'react'
type Row={rank:number;symbol:string;name:string;bias:'LONG'|'SHORT';change:number;lastPrice:number;futurePrice:number;rvol:number;volume:number;avgVolume20:number;breakout:string;signalTime:string;score:number;setup:string;dailyHigh:number;prevDayHigh:number;prevDayLow:number}
type Index={title:string;value:number|null;change:number|null}
type R={ok:boolean;candidates?:Row[];indexes?:Index[];timestamp?:string;error?:string;scanned?:number;universeCount?:number;diagnostics?:any;filter?:any}
const empty:Index[]=[{title:'NIFTY 50',value:null,change:null},{title:'BANK NIFTY',value:null,change:null},{title:'NIFTY MIDCAP',value:null,change:null},{title:'INDIA VIX',value:null,change:null}]
export default function Home(){
 const[rows,setRows]=useState<Row[]>([]),[indexes,setIndexes]=useState(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updated,setUpdated]=useState(''),[q,setQ]=useState(''),[side,setSide]=useState<'ALL'|'LONG'|'SHORT'>('ALL'),[diag,setDiag]=useState<any>(null)
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/market',{cache:'no-store'}),d:R=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Scanner unavailable');setRows(d.candidates??[]);setIndexes(d.indexes??empty);setUpdated(d.timestamp??'');setDiag(d.diagnostics??null)}catch(e){setError(e instanceof Error?e.message:'Scanner unavailable')}finally{setLoading(false)}}
 useEffect(()=>{load();const t=window.setInterval(load,30000);return()=>clearInterval(t)},[])
 const shown=useMemo(()=>rows.filter(x=>(side==='ALL'||x.bias===side)&&`${x.symbol} ${x.name}`.toLowerCase().includes(q.toLowerCase())),[rows,side,q])
 const longs=rows.filter(x=>x.bias==='LONG').length,shorts=rows.filter(x=>x.bias==='SHORT').length
 return <main className="shell">
  <header className="topbar"><div className="brand"><div className="logo">PT</div><div><div className="brand-title">FILTER SCANNER</div><div className="brand-sub">F&O volume + cash breakout + daily high</div></div></div><div className="top-actions"><span className="market-status"><i/> Market data: {loading?'Scanning…':error?'Offline':'LIVE'}</span><button className="refresh" onClick={load}>↻ Refresh</button></div></header>
  <section className="hero"><div><div className="eyebrow">LIVE → EXACT FILTER SCANNER</div><h1>Stocks that pass <span>all filters.</span></h1><p>Stock passes all of the below filters in the futures segment. Cash conditions use the corresponding NSE cash/underlying price series.</p></div><div className="regime-card"><div className="small-label">3 ACTIVE FILTERS</div><div className="regime">FUTURES + CASH <b>✓</b></div><div className="muted">Volume ×2 SMA + PDH/PDL breakout + Daily High &gt; 50</div></div></section>
  <section className="index-grid">{indexes.map(x=><IndexCard key={x.title} title={x.title} value={x.value==null?'—':x.value.toLocaleString('en-IN',{maximumFractionDigits:2})} change={x.change==null?'—':`${x.change>=0?'+':''}${x.change.toFixed(2)}%`} positive={(x.change??0)>=0}/>)}</section>
  <section className="control-row"><div className="tabs"><button className="active">LIVE</button></div><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search stock..."/></div><button className={`filter ${side==='ALL'?'on':''}`} onClick={()=>setSide('ALL')}>ALL</button><button className={`filter ${side==='LONG'?'on':''}`} onClick={()=>setSide('LONG')}>● BUY</button><button className={`filter short ${side==='SHORT'?'on':''}`} onClick={()=>setSide('SHORT')}>● SELL</button></section>
  <section className="stats-row"><Stat label="STOCKS PASSING" value={loading?'—':String(rows.length)} note="All 3 scanner filters passed"/><Stat label="BUY" value={String(longs)} note="5M high > 1 day ago high"/><Stat label="SELL" value={String(shorts)} note="5M low < 1 day ago low"/><Stat label="ACTIVE FILTERS" value="03" note="Volume + cash OR + daily high"/></section>
  <section className="content-grid"><div className="panel candidates-panel"><div className="panel-head"><div><div className="panel-title">STOCKS PASSING ALL FILTERS</div><div className="panel-sub">FUTURES: 5 MINUTE VOLUME &gt; 5 MINUTE SMA(VOLUME,20) × 2 • CASH: 5 MINUTE HIGH &gt; 1 DAY AGO HIGH OR 5 MINUTE LOW &lt; 1 DAY AGO LOW • DAILY HIGH &gt; 50</div></div><span className="live-pill"><i/> {loading?'SCANNING':error?'ERROR':'LIVE'}</span></div>
   <div className="table-wrap"><table><thead><tr><th>#</th><th>STOCK</th><th>SIGNAL</th><th>5M RVOL</th><th>5M VOLUME</th><th>BREAKOUT</th><th>DAY HIGH</th><th>PRICE</th><th>TIME</th></tr></thead><tbody>{shown.map(x=><tr key={x.symbol}><td className="rank">{String(x.rank).padStart(2,'0')}</td><td><div className="stock"><strong>{x.symbol}</strong><span>{x.name}</span></div></td><td><span className={`bias ${x.bias==='LONG'?'long':'short'}`}>{x.bias==='LONG'?'↑ BUY':'↓ SELL'}</span></td><td className="volume">{x.rvol.toFixed(2)}×</td><td>{x.volume.toLocaleString('en-IN')}</td><td><span className="setup">{x.breakout}</span></td><td>{x.dailyHigh.toLocaleString('en-IN',{maximumFractionDigits:2})}</td><td>{x.lastPrice.toLocaleString('en-IN',{maximumFractionDigits:2})}</td><td>{new Date(x.signalTime).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:false})}</td></tr>)}{!loading&&!shown.length&&<tr><td colSpan={9} style={{padding:36,textAlign:'center'}}>{error||'No stock currently passes all filters.'}</td></tr>}</tbody></table></div></div>
   <aside className="panel sector-panel"><div className="panel-head"><div><div className="panel-title">SCANNER FILTERS</div><div className="panel-sub">All conditions are AND unless stated OR</div></div></div><Rule n="01" title="FUTURES VOLUME" text="5 MINUTE Volume > 5 MINUTE SMA(Volume,20) × 2"/><Rule n="02" title="CASH — ANY 1" text="5 MINUTE High > 1 day ago High OR 5 MINUTE Low < 1 day ago Low"/><Rule n="03" title="DAILY HIGH" text="Daily High > 50"/><Rule n="04" title="RESULT" text="Stock is shown only when all three filters pass"/></aside></section>
  <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><div className="panel-title">SCAN DIAGNOSTICS</div><div className="panel-sub">Live rejection counts — useful when zero stocks pass</div></div></div><div className="status-grid"><Status label="F&O UNIVERSE" value={diag?.universe??'—'}/><Status label="QUOTE MATCHED" value={diag?.quoteMatched??'—'}/><Status label="DAY HIGH > 50" value={diag?.dailyHighPass??'—'}/><Status label="CASH BREAKOUT PASS" value={diag?.cashBreakoutPass??'—'}/><Status label="VOLUME PASS" value={diag?.volumePass??'—'}/><Status label="FINAL PASS" value={diag?.finalPass??'—'}/><Status label="API ERRORS" value={diag?.errors??'—'}/></div><div className="last">Last update: {updated?new Date(updated).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}):'—'}</div></section>
 </main>
}
function IndexCard({title,value,change,positive}:{title:string;value:string;change:string;positive:boolean}){return <div className="index-card"><div className="small-label">{title}</div><strong style={{fontSize:24,display:'block',marginTop:12}}>{value}</strong><span className={positive?'up':'down'}>{change}</span></div>}
function Stat({label,value,note}:{label:string;value:string;note:string}){return <div className="stat-card"><div className="small-label">{label}</div><strong>{value}</strong><span>{note}</span></div>}
function Rule({n,title,text}:{n:string;title:string;text:string}){return <div className="sector"><div className="sector-top"><span>{n} • {title}</span></div><div className="muted" style={{marginTop:7,lineHeight:1.5}}>{text}</div></div>}
function Status({label,value}:{label:string;value:string|number}){return <div style={{border:'1px solid rgba(255,255,255,.08)',borderRadius:12,padding:14}}><div className="small-label">{label}</div><b style={{display:'block',marginTop:7}}>{value}</b></div>}
