'use client'
import { useEffect, useMemo, useState } from 'react'
type Candidate={rank:number;symbol:string;name:string;score:number;bias:'LONG'|'SHORT';change:number;lastPrice:number;rvol?:number;pdBreak?:string;signalTime?:string;trigger?:string;masterCandle?:boolean;openingCandle?:boolean;extremeVolume?:boolean;setup?:string}
type IndexQuote={title:string;value:number|null;change:number|null}
type Response={ok:boolean;candidates?:Candidate[];indexes?:IndexQuote[];timestamp?:string;error?:string}
const fallback:IndexQuote[]=[{title:'NIFTY 50',value:null,change:null},{title:'BANK NIFTY',value:null,change:null},{title:'NIFTY MIDCAP',value:null,change:null},{title:'INDIA VIX',value:null,change:null}]
export default function Home(){
 const[data,setData]=useState<Candidate[]>([]),[indexes,setIndexes]=useState(fallback),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updated,setUpdated]=useState(''),[query,setQuery]=useState(''),[side,setSide]=useState<'ALL'|'LONG'|'SHORT'>('ALL')
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/market',{cache:'no-store'});const d:Response=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Market data unavailable');setData(d.candidates??[]);setIndexes(d.indexes??fallback);setUpdated(d.timestamp??new Date().toISOString())}catch(e){setError(e instanceof Error?e.message:'Unable to load market data')}finally{setLoading(false)}}
 useEffect(()=>{load();const t=window.setInterval(load,30000);return()=>window.clearInterval(t)},[])
 const rows=useMemo(()=>data.filter(x=>(side==='ALL'||x.bias===side)&&`${x.symbol} ${x.name}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.score-a.score),[data,side,query])
 const buys=data.filter(x=>x.bias==='LONG').length,sells=data.filter(x=>x.bias==='SHORT').length,ext=data.filter(x=>x.extremeVolume).length,master=data.filter(x=>x.masterCandle).length
 return <main className="shell">
  <header className="topbar"><div className="brand"><div className="logo">PT</div><div><div className="brand-title">PRIME TECHNICAL L-1</div><div className="brand-sub">Opening + Master Before 10AM</div></div></div><div className="top-actions"><span className="market-status"><i/> Market data: {loading?'Connecting…':error?'Offline':'LIVE'}</span><button className="refresh" onClick={load}>↻ Refresh</button></div></header>
  <section className="hero"><div><div className="eyebrow">LIVE → NSE F&O PRIME TECHNICAL SCANNER</div><h1>Find the stocks <span>before the move.</span></h1><p>5-minute Prime Technical L-1: 09:15 opening candle OR Master Candle + Extreme Volume + major-level breakout. No new signals after 10:00 AM.</p></div><div className="regime-card"><div className="small-label">SIGNAL WINDOW</div><div className="regime">09:15–09:55 <b>●</b></div><div className="muted">No new signal from 10:00</div></div></section>
  <section className="index-grid">{indexes.map(x=><IndexCard key={x.title} title={x.title} value={x.value==null?'—':x.value.toLocaleString('en-IN',{maximumFractionDigits:2})} change={x.change==null?'—':`${x.change>=0?'+':''}${x.change.toFixed(2)}%`} positive={(x.change??0)>=0}/>)}</section>
  <section className="control-row"><div className="tabs"><button className="active">LIVE</button></div><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search stock..."/></div><button className={`filter ${side==='ALL'?'on':''}`} onClick={()=>setSide('ALL')}>ALL</button><button className={`filter ${side==='LONG'?'on':''}`} onClick={()=>setSide('LONG')}>● LONG</button><button className={`filter short ${side==='SHORT'?'on':''}`} onClick={()=>setSide('SHORT')}>● SHORT</button></section>
  <section className="stats-row"><Stat label="L-1 CANDIDATES" value={String(data.length)} note={loading?'Scanning NSE F&O…':`${data.length} qualified signals`}/><Stat label="BUY SIGNALS" value={String(buys)} note="Bullish major-high break"/><Stat label="SELL SIGNALS" value={String(sells)} note="Bearish major-low breakdown"/><Stat label="EXTREME / MASTER" value={`${ext} / ${master}`} note="RVOL ≥ 2.50× / Master Candle"/></section>
  <section className="content-grid"><div className="panel candidates-panel"><div className="panel-head"><div><div className="panel-title">PRIME TECHNICAL L-1 SIGNALS</div><div className="panel-sub">09:15 OPENING OR MASTER CANDLE • EXTREME RVOL ≥ 2.50× • PDH / PDL / WEEKLY / MONTHLY / 52W / ATH</div></div><span className="live-pill"><i/> {loading?'SCANNING':error?'ERROR':'LIVE'}</span></div>
   <div className="table-wrap"><table><thead><tr><th>#</th><th>STOCK</th><th>SIGNAL</th><th>TRIGGER</th><th>BREAKOUT</th><th>RVOL</th><th>SCORE</th><th>TIME</th><th>PRICE</th></tr></thead><tbody>{rows.map(c=><tr key={c.symbol}><td className="rank">{String(c.rank||0).padStart(2,'0')}</td><td><div className="stock"><strong>{c.symbol}</strong><span>{c.name}</span></div></td><td><span className={`bias ${c.bias==='LONG'?'long':'short'}`}>{c.bias==='LONG'?'↑ BUY':'↓ SELL'}</span></td><td><span className="setup">{c.trigger||'—'}{c.masterCandle?' + MASTER':''}</span></td><td><b>{c.pdBreak||'—'}</b></td><td className="volume">{c.rvol?.toFixed(2)??'—'}×</td><td><Score value={c.score}/></td><td>{c.signalTime?new Date(c.signalTime).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:false}):'—'}</td><td>{c.lastPrice?.toLocaleString('en-IN',{maximumFractionDigits:2})??'—'}</td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={9} style={{padding:32,textAlign:'center'}}>{error||'No Prime Technical L-1 signal right now.'}</td></tr>}</tbody></table></div></div>
   <aside className="panel sector-panel"><div className="panel-head"><div><div className="panel-title">L-1 RULES</div><div className="panel-sub">Exact signal structure</div></div></div>{[['01','09:15 OPENING','Extreme Volume + Bull/Bear + Major Level'],['02','MASTER CANDLE','Range ≥ 1.5× previous 5 candles'],['03','EXTREME VOLUME','RVOL ≥ 2.50×'],['04','BUY','High ≥ PDH / Weekly / Monthly / 52W / ATH'],['05','SELL','Low ≤ PDL / Weekly / Monthly / 52W / ATL'],['06','TIME','Signals only 09:15–09:55']].map(([n,t,s])=><div className="sector" key={n}><div className="sector-top"><span>{n} • {t}</span></div><div className="muted" style={{marginTop:7}}>{s}</div></div>)}</aside></section>
  <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><div className="panel-title">SCANNER STATUS</div><div className="panel-sub">Upstox live + historical data engine</div></div><span className="live-pill"><i/> L-1 ACTIVE</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12}}><Status label="TIMEFRAME" value="5 MIN"/><Status label="RVOL THRESHOLD" value="2.50×"/><Status label="MASTER RANGE" value="1.50×"/><Status label="LAST UPDATE" value={updated?new Date(updated).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}):'—'}/></div></section>
 </main>
}
function IndexCard({title,value,change,positive}:{title:string;value:string;change:string;positive:boolean}){return <div className="index-card"><div className="small-label">{title}</div><strong style={{fontSize:24,display:'block',marginTop:12}}>{value}</strong><span className={positive?'up':'down'}>{change}</span></div>}
function Stat({label,value,note}:{label:string;value:string;note:string}){return <div className="stat-card"><div className="small-label">{label}</div><strong>{value}</strong><span>{note}</span></div>}
function Score({value}:{value:number}){return <span className="score" style={{fontWeight:800}}>{value}</span>}
function Status({label,value}:{label:string;value:string}){return <div style={{border:'1px solid rgba(255,255,255,.08)',borderRadius:12,padding:14}}><div className="small-label">{label}</div><b style={{display:'block',marginTop:7}}>{value}</b></div>}
